name: tow jobs

on: push

jobs:
        JobLinux:
                name: Job Linux
                runs-on: ubuntu-latest
                streps:
                        - name: Etapa 01
                        - uses: actions/checkout@v4
                        - name: Etapa 02
                          run:
                                  echo "$(cat REDME.md)"
                                  uname -a
         JobWindows:
                 name: Job Windowns
                 runs-on: Widows-latest
                 streps:
                        - name:Etapa 04
                        - uses: actions/checkout@v4
                        - name: Etapa 04
                        run:
                               echo "$(cat REDME.md)"
                                  uname -a
                       
